### ISSUE TITLE
[BUG] Image Page Doesn't Load Images

### ISSUE THREAD

**Issue by JLipnerPitt** [Particle1904/DatasetHelpers#26]
### Bug Description
Images don't load when a folder is selected.

![image](https://github.com/Particle1904/DatasetHelpers/assets/122459494/b64f1f6e-ad08-4aeb-a91c-d84388e108c6)

This is the desktop version.

**Comment by WorldEntityGravity** [comment]
I have the same problem, here is the log:
`Exception Details
=================
Date and Time: 2024-06-02 10:48:49
Source: System.Private.CoreLib
Message: The input string '11475168_115_6325' was not in a correct format.
Help Link: 
HResult: -2146233033

Stack Trace
============
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Int32.Parse(String s)
   at DatasetProcessor.ViewModels.GalleryViewModel.<>c.<LoadImagesFromInputFolder>b__18_1(String x) in E:\dev\DatasetHelpers\DatasetProcessor\ViewModels\GalleryViewModel.cs:line 130
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.Fill(Buffer`1 buffer, Span`1 destination)
   at System.Linq.OrderedEnumerable`1.ToList()
   at DatasetProcessor.ViewModels.GalleryViewModel.LoadImagesFromInputFolder() in E:\dev\DatasetHelpers\DatasetProcessor\ViewModels\GalleryViewModel.cs:line 130

Target Site
============
Declaring Type: System.Number
Method Name: ThrowFormatException

Additional Information
======================
`

"11475168_115_6325" mentioned is the name of the first image (.jpg) in the folder.

**Comment by Particle1904** [comment]
The program tried to sort the images by a crescent number but the image name is not in a valid format, you need to rename your files using the process tags page.
